### PR TITLE
Event Photo Upload Notifications (#111) and User Deletion Notifications (#112)

### PR DESCRIPTION
**Pull request by spt1224**
Unit testing to follow tomorrow once I've researched how to properly unit test triggered events and notifications.

This builds on issue #108 (PR #117), so should finalize that PR first.

### CODE REVIEW

**Comment by spt1224** [comment]
Test cases have been pushed.

**Comment by ngm** [comment]
@spt1224 Thanks Sean, the notification is being sent fine.

However, when the user is deleted, the notification shows 'Deleted User' as the user's name.

User details are anonymised when the user is deleted - so it looks as if the email is sent after this anonymisation takes place.  In the notification we need to see the name of the user before it has been anonymised.

**Comment by ngm** [comment]
@spt1224 For the in-app notification, the deleted user notification has the name of the deleted user hyperlinked, but the link doesn't go anywhere.  Can the link be removed just for this notification?

**Comment by ngm** [comment]
Image upload notification works well - I like the extra checks for not notifying the user if they uploaded the image themselves, and throttling to stop multiple notifications being sent!

**Pull request merged**
