### PR TITLE
DOT-1369 groups events devices update

### PR DESCRIPTION
**Pull request by edwh**
This introduces an event for devices being created/updated, listens on it, and uses that to maintain a devices_updated_at field in the party and group.

### CODE REVIEW

**Review by ngm — COMMENTED** [review]
Looks great, the event approach is very nice and clean.

Doesn't look like this is exposed to the via the APIs yet - presume we're waiting to do this as per the ticket, following clarficiation from RT developers as to whether they are in a position to use a new field.

**Comment by ngm** [comment]
Aha, I was looking at the API endpoints:

/api/groups/network?api_token=x
/api/events/network?api_token=x

As these are what Repair Together access.  I don't seem to see it there even after adding a device.  

That said, after chatting with RT, they would prefer to use the existing updated_at field, and have it represent updates to either group/event properties OR device updates.  So we should return updated_at from these API calls as the greater of updated_at and devices_updated_at.  (This would avoid us having to run a script to set devices_updated_at for all groups/events too.)

**Comment by edwh** [comment]
Ok - I've made those two API calls return the max value.  See what you think.

**Comment by ngm** [comment]
@edwh Code all looks good, just one odd thing for me - when running locally, I get the following returned:

image

created_at is an empty array for some reason, and updated_at is a string.

On production at present, we get the following returned:

image

both created_at and updated_at are objects with properties of date, timezone_type, and timezone.

I'm not sure why that is - presumably that's how a Carbon datetime is serialized.  I don't know why this is happening one way on prod, but not locally - only think I can think is something has changed between PHP versions?

I think wrapping the dates e.g. new \Carbon\Carbon($group->max_updated_at_devices_updated_at) might preserve the existing behaviour.

**Comment by edwh** [comment]
That is a bit odd.  Fix pushed as you suggest.

I tend to return dates in ISO 8601, as I think that's easier for a client to parse.  But we should preserve the existing behavour.

**Comment by ngm** [comment]
> I tend to return dates in ISO 8601, as I think that's easier for a client to parse. But we should preserve the existing behavour.

Agreed (to both points).

**Review by ngm — APPROVED** [review]

**Pull request merged**
