### PR TITLE
RES-1883 Remove useful URLs feature

### PR DESCRIPTION
**Pull request by edwh**
This feature was very rarely used, and has been retired.  This PR removes the code and adds a migration to drop the table.

### CODE REVIEW

**Review by ngm — CHANGES_REQUESTED** [review]
Not an insignificant amount of code, for such an unused feature!

I notice that the migration is empty.  I presume we just need to be dropping the device_urls table?

**Comment by edwh** [comment]
> Not an insignificant amount of code, for such an unused feature!
> 
> I notice that the migration is empty. I presume we just need to be dropping the device_urls table?

Added

**Comment by ngm** [comment]
@edwh Did you mean to close this PR?

**Comment by edwh** [comment]
@ngm No, I didn't.  Re-opened so you can review the migration.

**Pull request merged**
