### PR TITLE
DOT-1383 Fix export

### PR DESCRIPTION
**Pull request by edwh**
I broke this when removing code I thought was dead.  The old code used DeviceController::search, which no longer exists.  

I'm not sure that's necessary or the best way to do it.  Can you think about whether there is any reason not to return all the devices?

### CODE REVIEW

**Comment by ngm** [comment]
> I broke this when removing code I thought was dead. The old code used DeviceController::search, which no longer exists.
> 
> I'm not sure that's necessary or the best way to do it. Can you think about whether there is any reason not to return all the devices?

The reason would be so that the export matches the way in which you have filtered the list. What's your argument for not doing that?  (One argument could be that you can filter it more easily in a spreadsheet following your export.)

In the interest of getting the export working again, to begin with let's just re-enable it as a full export if this is quicker.  Given where the button currently is, it doesn't indicate that the export is filtered.

Then, in a future sprint, we can determine whether there is any utility in a filtered export.

**Comment by edwh** [comment]
Then let's do a full export.  Are you OK with the code?

**Review by ngm — CHANGES_REQUESTED** [review]
The code for the export looks good, can you confirm check though that the Export Data button is only present for Admins?  (as per in the Jira ticket)

**Comment by edwh** [comment]
The Export button is there for everyone.  I've not changed that.

We could make it only visible for Admins, but I'm not sure it's part of 
this story, and I'm not sure there's much point given that anyone who 
cares can grab the data in other ways?

------ Original Message ------

**Comment by ngm** [comment]
> We could make it only visible for Admins, but I'm not sure it's part of this story, and I'm not sure there's much point given that anyone who cares can grab the data in other ways?

From the midsts of time I recall that via the download from https://therestartproject.org/download-dataset, you get the data without the model field.  Internally you get the full dataset, including the model field.  The reason (perhaps no longer valid and to be discussed), was the desire to keep the model field private as a potential business asset.  

So I think we lost the fact that the Export Data button was for admins only when we recently migrated this page to the new design.  Until we have a solidly groomed story on the export from the Fixometer page for non-admins, we should keep it for admins only.

**Comment by edwh** [comment]
Ok - change pushed.  Have a look?

------ Original Message ------

**Comment by ngm** [comment]
@edwh Looks good :+1:

**Pull request merged**
