### PR TITLE
RES-1896 Change "New Zealand" to "Aotearoa New Zealand"

### PR DESCRIPTION
**Pull request by edwh**

### CODE REVIEW

**Review by ngm — CHANGES_REQUESTED** [review]
I assume this will need to be changed based on what is in RES-1894?

**Comment by edwh** [comment]
> I assume this will need to be changed based on what is in RES-1894?

I thought we were just changing the NZ country name throughout (without prejudice to other political disputes) so that we didn't have to worry about how to get the relevant locale set for a network which doesn't have a vanity domain?

So I think RES-1894  is separate,

**Comment by ngm** [comment]
Yes to all the above, but in RES-1984 I saw that the countries list had moved out of Fixometer and into Lang files.

**Comment by edwh** [comment]
> Yes to all the above, but in RES-1984 I saw that the countries list had moved out of Fixometer and into Lang files.

Ah, yes.  You're right, this will be a different fix once that goes in.  Merge time.

**Review by ngm — APPROVED** [review]

**Pull request merged**
