### PR TITLE
DOT-1256 Position language bar correctly

### PR DESCRIPTION
**Pull request by edwh**
Simple CSS fix to position language switcher. Tested on Dashboard page only.

I'm not sure where you put CSS generally, but there's already some for the language-bar, so I've put it near that.

### CODE REVIEW

**Comment by edwh** [comment]
That's showing an odd comment change, but it looks the same.

**Comment by edwh** [comment]
Ok.  Do you check in the built CSS too or does that happen as part of 
deployment?

------ Original Message ------

**Comment by ngm** [comment]
> Ok. Do you check in the built CSS too or does that happen as part of deployment?

Yes, check in the built CSS too please.  Not currently built as part of deployment.

**Comment by edwh** [comment]
Ok - back to you for review.

------ Original Message ------

**Pull request merged**
